SocialNetwork/SocialNetwork/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SocialNetwork.Models;

namespace SocialNetwork.Controllers
{
    public class CommentsController : Controller
    {
        private readonly PhotoSocialNetwork_DB db = new PhotoSocialNetwork_DB();

        //GET: Comments Partial View within the Photos/Details view
        [ChildActionOnly]
        public PartialViewResult _CommentPhoto(int photoId)
        {
            var comments = db.Comments.Where(c => c.photoId == photoId).ToList();

            ViewBag.PhotoId = photoId;

            return PartialView(comments.ToList());
        }

        //POST: Creates comment
        [HttpPost]
        public PartialViewResult _CommentPhoto(Comment comment, int photoId)
        {
            comment.username = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(Session["username"].ToString());

            db.Comments.Add(comment);
            db.SaveChanges();

            var comments = db.Comments.Where(c => c.photoId == photoId).ToList();

            ViewBag.PhotoId = photoId;

            return PartialView("_CommentPhoto.cshtml", comments.ToList());
        }

        // GET: Comments/Create
        public PartialViewResult Create(int _photoId)
        {
            //Create new comment
            Comment newComment = new Comment()
            {
                photoId = _photoId,
                username = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(Session["username"].ToString())
            };

            ViewBag.PhotoId = _photoId;

            return PartialView("~/Views/Shared/_PostComment.cshtml");
        }

        // POST: Comments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "commentId,photoId,username,text")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.photoId = new SelectList(db.Photos, "photoId", "title", comment.photoId);
            return View(comment);
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.photoId = new SelectList(db.Photos, "photoId", "title", comment.photoId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "commentId,photoId,username,text")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.photoId = new SelectList(db.Photos, "photoId", "title", comment.photoId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Comment comment = db.Comments.Find(id);

            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Details", "Photo", new { id = comment.photoId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SocialNetwork/SocialNetwork/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SocialNetwork.Models;

namespace SocialNetwork.Controllers
{
    public class PhotosController : Controller
    {
        private readonly PhotoSocialNetwork_DB db = new PhotoSocialNetwork_DB();

        // GET: Photos
        public ActionResult Index()
        {
            return View("Index", db.Photos.ToList());
        }

        //GET: Render _PhotoGallery Partial View to display photo gallery in Home/Index page
        [ChildActionOnly]
        public ActionResult PhotoGallery(int num = 0)
        {
            //In the view, display the latest photos when num is greater than 0
            //Otherwise, display all photos
            List<Photo> photos;

            if (num == 0)
            {
                photos = db.Photos.ToList();
            }
            else
            {
                photos = db.Photos
                    .OrderByDescending(p => p.createdDate)
                    .Take(num).ToList();
            }

            return PartialView("~/Views/Shared/_PhotoGallery.cshtml", photos);
        }

        //Grabs the photo file to its associated photo ID
        public ActionResult GetImage(int photoId)
        {
            Photo requestedPhoto = db.Photos.FirstOrDefault(p => p.photoId == photoId);

            if (requestedPhoto != null)
            {
                return File(requestedPhoto.photoFilePath, requestedPhoto.imageMimeType);
            }
            else
            {
                return null;
            }
        }

        // GET: Photos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Photo photo = db.Photos.Find(id);

            if (photo == null)
            {
                return HttpNotFound();
            }

            return View("Details", photo);
        }

        // GET: Photos/Create
        public ActionResult Create()
        {
            if (Session["username"] != null)
            {
                Photo newPhoto = new Photo
                {
                    username = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(Session["username"].ToString()),
                    createdDate = DateTime.Today,
                    modifiedDate = DateTime.Today
                };

                return View(newPhoto);
            }
            else
            {
                TempData["LoginMessage"] = "You must be logged in to do that.";

                return RedirectToAction("Login", "Account");
            }
        }

        // POST: Photos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Photo photo, HttpPostedFileBase image)
        {
            photo.username = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(Session["username"].ToString());
            photo.createdDate = DateTime.Today;
            photo.modifiedDate = DateTime.Today;

            if (ModelState.IsValid)
            {
                //Read photo content type and file size, then save the photo
                if (image != null)
                {
                    photo.imageMimeType = image.ContentType;

                    string filePath = Path.Combine(Server.MapPath("~/Images/"), image.FileName);
                    photo.photoFilePath = filePath;

                    photo.photoImage.SaveAs(filePath);
                    
                    //Need to save filepath and image.mimeType to database
                    //Consider rebuilding database
                }

                db.Photos.Add(photo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(photo);
        }

        // GET: Photos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "photoId,title,photoFile,imageMimeType,description,username,createdDate,modifiedDate")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(photo);
        }

        // GET: Photos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Photo photo = db.Photos.Find(id);

            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.Photos.Find(id);
            db.Photos.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SocialNetwork/SocialNetwork/Views/Shared/_AddComment.cshtml
@model SocialNetwork.Models.Comment

@{ 
    Layout = null;
}

@Html.ValidationSummary(true)

<div class="add-comment">
    <div class="">
        <div class="comment-edit-label">
            @Html.LabelFor(model => model.text)
        </div>
        <div class="comment-edit-field">
            @Html.EditorFor(model => model.text)
            @Html.ValidationMessageFor(model => model.text)
        </div>
    </div>

    <input type="submit" name="Post comment" value="Create" />
</div>

SocialNetwork/SocialNetwork/Views/Shared/_CommentPhoto.cshtml
@model IEnumerable<SocialNetwork.Models.Comment>

@{
    Layout = null;
}

<link href="~/Content/stylesheet.css" rel="stylesheet" />

@{
    AjaxOptions ajax = new AjaxOptions { UpdateTargetId = "all-comments" };
}

<h3 class="page-header">Comments</h3>
<br />
@using (Ajax.BeginForm("_CommentPhoto", new { photoId = ViewBag.photoId }, ajax))
{
    <div class="" id="all-comments">
        @foreach (var comment in Model)
        {
        <div class="" id="photo-comment">
            <div class="" id="photo-comment-username">
                @Html.DisplayFor(modelItem => comment.username)
            </div>

            <div class="" id="photo-comment-text">
                @Html.DisplayFor(modelItem => comment.text)
            </div>

            <br />
            @if (Session["username"] != null)
            {
                @Html.ActionLink("Delete comment", "Delete", "Comments", new { id = comment.commentId }, null)
            }
        </div>
        }

        <div class="" id="add-comment">
            @if (Session["username"] != null)
            {
                @Html.ActionLink("Create a comment", "Create", "Comments", new { photoId = ViewBag.photoId }, htmlAttributes: new { @class = "btn btn-primary" })
            }
            else
            {
                @Html.ActionLink("Login to comment", "Login", "Account", null, htmlAttributes: new { @class = "btn btn-primary" })
            }
        </div>
    </div>
}

SocialNetwork/SocialNetwork/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>

</head>
<body>
    <div class="navbar navbar-expand-sm navbar-dark bg-dark mb-2">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PhotoSocial", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto px-2">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })</li>
                </ul>
                @Html.Partial("~/Views/Shared/_LoginNavbar.cshtml")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Thomas Dam</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SocialNetwork/SocialNetwork/Views/Shared/_LoginNavbar.cshtml
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

@if (Session["username"] != null)
{

    using (Html.BeginForm("Logout", "Account", FormMethod.Post))
    {
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">@Html.ActionLink(" Welcome " + Session["username"] + "!", "Person", "Account", new { id = Session["id"] }, new { @class = "nav-link" })</li>
            @*<li class="nav-item"><a href="@Url.Action("Person", "Account", new { id = Session["id"] })"><i class="fas fa-user"></i>Welcome + @Session["username"] + !</a></li>*@
            <li class="nav-item">@Html.ActionLink("Log out", "Logout", "Account", null, new { @class = "nav-link" })</li>
        </ul>
    }
}
else
{
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">@Html.ActionLink("Login", "Login", "Account", null, new { @class = "nav-link" })</li>
        <li class="nav-item">@Html.ActionLink("Register", "Register", "Account", null, new { @class = "nav-link" })</li>
    </ul>
}

SocialNetwork/SocialNetwork/Views/Shared/_PhotoGallery.cshtml
@model IEnumerable<SocialNetwork.Models.Photo>

@{
    Layout = null;
}

<link href="~/Content/stylesheet.css" rel="stylesheet" />

<div class="container" id="photo-container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-6">
                <div class="card shadow" id="photo-gallery">

                    <h3 class="card-title">
                        @Html.DisplayFor(modelItem => item.title)
                    </h3>

                    @if (item.photoFilePath != null)
                    {
                        @*<img class="" src="@Url.Action("GetImage", "Photo", new { photoId = item.photoId})" />*@
                        <img class="card-img-top" id="photo-gallery-img" src="~/Images/@(item.photoFilePath)" />
                    }

                    <div class="card-body" id="photo-data">
                        <div>
                            <span class="card-text" id="display-label">
                                Uploaded by:
                            </span>
                            <span class="display-field">
                                @Html.DisplayFor(model => item.username)
                            </span>
                        </div>

                        <div>
                            <span class="card-text" id="display-label">
                                @Html.DisplayNameFor(model => model.createdDate):
                            </span>
                            <span class="display-field">
                                @Html.DisplayFor(model => item.createdDate)
                            </span>
                        </div>

                        <div>
                            <span class="card-text" id="display-label">
                                @Html.DisplayNameFor(model => model.modifiedDate):
                            </span>
                            <span class="display-field">
                                @Html.DisplayFor(model => item.modifiedDate)
                            </span>
                        </div>
                    </div>

                    @Html.ActionLink("Details", "Details", "Photos", new { id = item.photoId }, htmlAttributes: new { @class = "btn btn-primary" })
                </div>
            </div>

        }
    </div>
</div>